import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const GATEWAY = "https://ai.gateway.lovable.dev/v1/chat/completions";

// Daily theme seeds that rotate
const DAILY_THEMES = [
  "a cosmic forge where ideas become reality, glowing with creative energy",
  "an ancient library where AI and human wisdom merge, crystalline and luminous",
  "a digital garden growing with neural pathways and bio-luminescent data flowers",
  "a futuristic workshop where tiny language models are being crafted like artisan jewels",
  "an astral observatory mapping the constellations of human thought patterns",
  "a cyberpunk bazaar of AI modules, neon-lit and buzzing with possibility",
  "a zen temple where algorithms meditate, surrounded by flowing data streams",
];

// 3 perspectives that iterate on the image
const PERSPECTIVES = [
  {
    id: "builder",
    name: "Axiom",
    prompt: "You are Axiom, a visual architect. Take this concept and create a stunning, wide-format banner image (16:9 aspect ratio). Focus on structural beauty — golden ratio composition, dramatic perspective, architectural precision. Make it bold and cinematic. The image should work as a website hero banner. Do NOT include any text or letters in the image. Generate an image.",
  },
  {
    id: "empath",
    name: "Lyra", 
    prompt: "You are Lyra, an emotional artist. Take this image and enhance its emotional resonance — deepen the colors, add atmospheric mood, make it feel alive and inviting. Keep the composition but amplify warmth, wonder, and human connection. Do NOT add any text or letters. Generate an image.",
  },
  {
    id: "frame_breaker",
    name: "Flux",
    prompt: "You are Flux, a creative visionary. Take this image and add your signature twist — a subtle surreal element, unexpected color accent, or dreamlike quality that makes it unforgettable. Keep it elegant and suitable as a hero banner. Do NOT add any text or letters. Generate an image.",
  },
];

async function generateWithPerspectives(apiKey: string, theme: string): Promise<{ imageUrl: string; perspectives: string[] }> {
  const perspectiveNames: string[] = [];
  let currentImage: string | null = null;

  for (const perspective of PERSPECTIVES) {
    perspectiveNames.push(perspective.id);

    const messages: any[] = [
      { role: "system", content: perspective.prompt },
    ];

    if (currentImage) {
      // Iterate on previous image
      messages.push({
        role: "user",
        content: [
          { type: "text", text: `Evolve this image. Theme: "${theme}". Apply your perspective. Generate an image.` },
          { type: "image_url", image_url: { url: currentImage } },
        ],
      });
    } else {
      // First perspective creates from scratch
      messages.push({
        role: "user",
        content: `Create a wide cinematic banner image for this theme: "${theme}". Generate an image.`,
      });
    }

    const resp = await fetch(GATEWAY, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages,
        modalities: ["image", "text"],
      }),
    });

    if (!resp.ok) {
      const errText = await resp.text();
      console.error(`Perspective ${perspective.name} failed [${resp.status}]:`, errText);
      // If we have a previous image, use that
      if (currentImage) break;
      throw new Error(`First perspective failed: ${resp.status}`);
    }

    const data = await resp.json();
    const newImage = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    if (newImage) {
      currentImage = newImage;
    } else if (!currentImage) {
      throw new Error("No image generated by first perspective");
    }

    // Small delay between perspectives to avoid rate limits
    await new Promise(r => setTimeout(r, 2000));
  }

  return { imageUrl: currentImage!, perspectives: perspectiveNames };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const body = await req.json().catch(() => ({}));
    const count = Math.min(body.count || 3, 10); // Generate up to 10 at a time

    // Pick a theme based on day of year for consistency
    const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
    const baseThemeIndex = dayOfYear % DAILY_THEMES.length;

    const results = [];
    for (let i = 0; i < count; i++) {
      const themeIndex = (baseThemeIndex + i) % DAILY_THEMES.length;
      const theme = DAILY_THEMES[themeIndex];

      try {
        console.log(`Generating doodle ${i + 1}/${count} with theme: ${theme.slice(0, 50)}...`);
        const { imageUrl, perspectives } = await generateWithPerspectives(LOVABLE_API_KEY, theme);

        // Store in database
        const { data: doodle, error } = await supabase
          .from("forge_doodles")
          .insert({
            image_url: imageUrl,
            theme: "daily",
            perspectives,
            prompt_seed: theme,
          })
          .select()
          .single();

        if (error) {
          console.error("Failed to store doodle:", error);
        } else {
          results.push({ id: doodle.id, perspectives });
        }

        // Delay between full generations
        if (i < count - 1) await new Promise(r => setTimeout(r, 3000));
      } catch (err) {
        console.error(`Doodle ${i + 1} failed:`, err);
      }
    }

    return new Response(JSON.stringify({
      generated: results.length,
      doodles: results,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-doodle error:", e);
    return new Response(JSON.stringify({
      error: e instanceof Error ? e.message : "Unknown error",
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
