import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { streamAI } from "@/hooks/useSupabaseData";
import {
  Sparkles, Send, Loader2, CheckCircle2, Download,
  Code2, Cpu, Zap, Box, RotateCcw, Copy, Play,
  Atom, Brain, Radio, Workflow, Joystick, BarChart3,
  ChevronRight, FileCode, Package, Wand2
} from "lucide-react";

type GenerationDomain = "solver" | "ml-model" | "pipeline" | "signal" | "robotics" | "game-module";

interface GeneratedAsset {
  id: string;
  domain: GenerationDomain;
  name: string;
  description: string;
  spec: Record<string, any>;
  code: string;
  status: "generating" | "ready" | "deployed";
  timestamp: number;
}

const domainConfig: Record<GenerationDomain, { label: string; icon: any; color: string; placeholder: string; examples: string[] }> = {
  solver: { label: "Physics/Math Solver", icon: Atom, color: "text-cyan-500", placeholder: "Describe the solver you need…",
    examples: ["Lattice Boltzmann fluid solver for 2D cavity flow", "Runge-Kutta adaptive ODE integrator with error control", "Finite element solver for 2D heat equation with mesh refinement"] },
  "ml-model": { label: "ML Model Config", icon: Brain, color: "text-purple-500", placeholder: "Describe the model architecture…",
    examples: ["Lightweight image classifier for 10 classes, <5MB, mobile-ready", "Transformer encoder for sentiment analysis with 4 attention heads", "Autoencoder for anomaly detection on time-series sensor data"] },
  pipeline: { label: "Data Pipeline", icon: Workflow, color: "text-orange-500", placeholder: "Describe the data flow…",
    examples: ["CDC pipeline from PostgreSQL to Elasticsearch with transforms", "Real-time Kafka aggregator with 5-min tumbling windows", "ETL pipeline: S3 parquet → dedup → validate → Snowflake"] },
  signal: { label: "Signal Processor", icon: Radio, color: "text-green-500", placeholder: "Describe the signal processing chain…",
    examples: ["Adaptive noise canceller for ECG signals at 250Hz", "OFDM demodulator with channel estimation for 64 subcarriers", "Mel-spectrogram feature extractor for speech recognition"] },
  robotics: { label: "Robotics Controller", icon: Joystick, color: "text-rose-500", placeholder: "Describe the control system…",
    examples: ["PID cascade controller for quadcopter altitude hold", "Visual servoing controller for 6-DOF arm pick-and-place", "A* path planner with dynamic obstacle avoidance on 2D grid"] },
  "game-module": { label: "Game AI Module", icon: Zap, color: "text-yellow-500", placeholder: "Describe the game AI behavior…",
    examples: ["Behavior tree for guard NPC with patrol/chase/search states", "Procedural terrain generator with biome blending", "Dynamic difficulty adjustment based on player performance metrics"] },
};

// Simulated generation with realistic output
function simulateGeneration(domain: GenerationDomain, prompt: string): Promise<GeneratedAsset> {
  return new Promise((resolve) => {
    const configs: Record<GenerationDomain, () => { name: string; description: string; spec: Record<string, any>; code: string }> = {
      solver: () => {
        const name = prompt.includes("fluid") ? "LatticeBoltzmannSolver2D" : prompt.includes("heat") ? "FEMHeatSolver2D" : "AdaptiveRK45Integrator";
        return {
          name, description: `Auto-generated solver: ${prompt.slice(0, 80)}`,
          spec: {
            type: "numerical-solver", method: prompt.includes("fluid") ? "Lattice Boltzmann (D2Q9)" : prompt.includes("heat") ? "FEM (P1 elements)" : "RK45 Dormand-Prince",
            precision: "float64", convergence: "1e-8 relative tolerance", parallelism: "SIMD-vectorized inner loops",
            inputs: ["domain_config", "boundary_conditions", "initial_state", "dt", "t_end"],
            outputs: ["solution_field", "error_history", "convergence_log", "timing_stats"],
          },
          code: `// ${name} — Auto-generated by Forge AI
import { Float64Array2D, BoundaryCondition, SolverConfig } from '@soupyforge/core';

export class ${name} {
  private grid: Float64Array2D;
  private config: SolverConfig;

  constructor(config: SolverConfig) {
    this.config = config;
    this.grid = new Float64Array2D(config.nx, config.ny);
    this.initializeBoundary(config.boundary);
  }

  private initializeBoundary(bc: BoundaryCondition): void {
    // Apply Dirichlet/Neumann conditions
    for (let i = 0; i < this.config.nx; i++) {
      this.grid.set(i, 0, bc.south(i * this.config.dx));
      this.grid.set(i, this.config.ny - 1, bc.north(i * this.config.dx));
    }
  }

  step(dt: number): { maxResidual: number; converged: boolean } {
    let maxRes = 0;
    const { nx, ny, dx, dy } = this.config;

    for (let i = 1; i < nx - 1; i++) {
      for (let j = 1; j < ny - 1; j++) {
        const laplacian = (
          (this.grid.get(i+1,j) - 2*this.grid.get(i,j) + this.grid.get(i-1,j)) / (dx*dx) +
          (this.grid.get(i,j+1) - 2*this.grid.get(i,j) + this.grid.get(i,j-1)) / (dy*dy)
        );
        const update = this.grid.get(i,j) + dt * this.config.alpha * laplacian;
        const residual = Math.abs(update - this.grid.get(i,j));
        maxRes = Math.max(maxRes, residual);
        this.grid.set(i, j, update);
      }
    }
    return { maxResidual: maxRes, converged: maxRes < 1e-8 };
  }

  solve(tEnd: number): Float64Array2D {
    const dt = this.config.dt;
    let t = 0;
    while (t < tEnd) {
      const { converged } = this.step(dt);
      t += dt;
      if (converged) break;
    }
    return this.grid;
  }

  getField(): Float64Array2D { return this.grid; }
}`,
        };
      },
      "ml-model": () => {
        const name = prompt.includes("classif") ? "LiteClassifier" : prompt.includes("anomal") ? "AnomalyAutoencoder" : "MicroTransformer";
        return {
          name, description: `Auto-generated model: ${prompt.slice(0, 80)}`,
          spec: {
            architecture: prompt.includes("classif") ? "MobileNetV3-Small variant" : prompt.includes("anomal") ? "Conv1D Autoencoder" : "4-head Transformer Encoder",
            params: prompt.includes("classif") ? "2.1M" : prompt.includes("anomal") ? "890K" : "12M",
            inputShape: prompt.includes("classif") ? "[B, 3, 224, 224]" : prompt.includes("anomal") ? "[B, seq_len, features]" : "[B, seq_len]",
            outputShape: prompt.includes("classif") ? "[B, num_classes]" : prompt.includes("anomal") ? "[B, seq_len, features]" : "[B, seq_len, d_model]",
            quantizable: true, exportFormats: ["ONNX", "TFLite", "CoreML"],
          },
          code: `// ${name} — Auto-generated by Forge AI
import torch
import torch.nn as nn

class ${name}(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        ${prompt.includes("classif") ? `
        # Lightweight classification head
        self.backbone = nn.Sequential(
            nn.Conv2d(3, 16, 3, stride=2, padding=1), nn.ReLU6(),
            nn.Conv2d(16, 32, 3, stride=2, padding=1), nn.ReLU6(),
            nn.Conv2d(32, 64, 3, stride=2, padding=1), nn.ReLU6(),
            nn.AdaptiveAvgPool2d(1),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(), nn.Linear(64, config.num_classes)
        )` : prompt.includes("anomal") ? `
        # Conv1D Autoencoder
        self.encoder = nn.Sequential(
            nn.Conv1d(config.features, 32, 3, padding=1), nn.ReLU(),
            nn.Conv1d(32, 16, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv1d(16, 8, 3, stride=2, padding=1), nn.ReLU(),
        )
        self.decoder = nn.Sequential(
            nn.ConvTranspose1d(8, 16, 3, stride=2, padding=1, output_padding=1), nn.ReLU(),
            nn.ConvTranspose1d(16, 32, 3, stride=2, padding=1, output_padding=1), nn.ReLU(),
            nn.Conv1d(32, config.features, 3, padding=1),
        )` : `
        # Transformer Encoder
        self.embedding = nn.Embedding(config.vocab_size, config.d_model)
        self.pos_enc = nn.Parameter(torch.randn(1, config.max_len, config.d_model))
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=config.d_model, nhead=4, dim_feedforward=config.d_model*4, batch_first=True
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=4)`}

    def forward(self, x):
        ${prompt.includes("classif") ? "return self.classifier(self.backbone(x))" : prompt.includes("anomal") ? "z = self.encoder(x)\n        return self.decoder(z)" : "x = self.embedding(x) + self.pos_enc[:, :x.size(1)]\n        return self.encoder(x)"}`,
        };
      },
      pipeline: () => ({
        name: "AutoPipeline", description: `Auto-generated pipeline: ${prompt.slice(0, 80)}`,
        spec: {
          nodes: [
            { name: "Source Connector", type: "source" },
            { name: "Schema Validator", type: "validate" },
            { name: "Transform Engine", type: "transform" },
            { name: "Quality Gate", type: "validate" },
            { name: "Target Writer", type: "sink" },
          ],
          throughput: "500K rows/sec", latency: "Sub-second", reliability: "Exactly-once",
        },
        code: `// AutoPipeline — Auto-generated by Forge AI
import { Pipeline, Source, Transform, Sink, Validator } from '@soupyforge/pipeline';

export const pipeline = new Pipeline('auto-pipeline')
  .source(new Source.Auto({ config: 'detect' }))
  .validate(new Validator.Schema({ strict: true, evolve: 'backward-compatible' }))
  .transform(new Transform.Map(record => ({
    ...record,
    processed_at: Date.now(),
    hash: computeHash(record),
  })))
  .validate(new Validator.Quality({
    nullThreshold: 0.01,
    duplicateCheck: true,
    anomalyDetection: 'statistical',
  }))
  .sink(new Sink.Auto({ 
    mode: 'upsert',
    batchSize: 1000,
    retryPolicy: { maxRetries: 3, backoff: 'exponential' },
  }));

pipeline.onError((err, record) => {
  deadLetterQueue.push({ error: err.message, record, timestamp: Date.now() });
});

export default pipeline;`,
      }),
      signal: () => ({
        name: "AutoSignalChain", description: `Auto-generated signal processor: ${prompt.slice(0, 80)}`,
        spec: {
          stages: ["Input Buffer", "Pre-filter", "Core Algorithm", "Post-filter", "Output"],
          sampleRate: "configurable", precision: "float64", realTime: true,
        },
        code: `// AutoSignalChain — Auto-generated by Forge AI
export class AutoSignalChain {
  private sampleRate: number;
  private bufferSize: number;
  private inputBuffer: Float64Array;
  private outputBuffer: Float64Array;

  constructor(sampleRate: number, bufferSize: number = 1024) {
    this.sampleRate = sampleRate;
    this.bufferSize = bufferSize;
    this.inputBuffer = new Float64Array(bufferSize);
    this.outputBuffer = new Float64Array(bufferSize);
  }

  process(input: Float64Array): Float64Array {
    // Stage 1: Pre-filter (DC removal + anti-alias)
    this.removeDC(input);
    
    // Stage 2: Core processing
    for (let i = 0; i < input.length; i++) {
      this.outputBuffer[i] = this.coreAlgorithm(input[i], i);
    }
    
    // Stage 3: Post-filter (smoothing)
    this.applySmoothing(this.outputBuffer);
    
    return this.outputBuffer;
  }

  private removeDC(buffer: Float64Array): void {
    let mean = 0;
    for (let i = 0; i < buffer.length; i++) mean += buffer[i];
    mean /= buffer.length;
    for (let i = 0; i < buffer.length; i++) buffer[i] -= mean;
  }

  private coreAlgorithm(sample: number, index: number): number {
    // Auto-configured processing kernel
    return sample; // Placeholder for domain-specific logic
  }

  private applySmoothing(buffer: Float64Array): void {
    const alpha = 0.1;
    for (let i = 1; i < buffer.length; i++) {
      buffer[i] = alpha * buffer[i] + (1 - alpha) * buffer[i - 1];
    }
  }
}`,
      }),
      robotics: () => ({
        name: "AutoController", description: `Auto-generated controller: ${prompt.slice(0, 80)}`,
        spec: {
          controlType: prompt.includes("PID") ? "PID Cascade" : prompt.includes("path") ? "Sampling-based Planner" : "State-Space Controller",
          updateRate: "1kHz", dof: "configurable", safetyLimits: true,
        },
        code: `// AutoController — Auto-generated by Forge AI
export class AutoController {
  private kp: number[];
  private ki: number[];
  private kd: number[];
  private integralError: number[];
  private prevError: number[];
  private dt: number;

  constructor(dof: number, dt: number = 0.001) {
    this.dt = dt;
    this.kp = new Array(dof).fill(10.0);
    this.ki = new Array(dof).fill(0.1);
    this.kd = new Array(dof).fill(1.0);
    this.integralError = new Array(dof).fill(0);
    this.prevError = new Array(dof).fill(0);
  }

  update(setpoint: number[], measurement: number[]): number[] {
    const output: number[] = [];
    for (let i = 0; i < setpoint.length; i++) {
      const error = setpoint[i] - measurement[i];
      this.integralError[i] += error * this.dt;
      this.integralError[i] = Math.max(-100, Math.min(100, this.integralError[i])); // anti-windup
      const derivative = (error - this.prevError[i]) / this.dt;
      
      output.push(
        this.kp[i] * error +
        this.ki[i] * this.integralError[i] +
        this.kd[i] * derivative
      );
      this.prevError[i] = error;
    }
    return output;
  }

  tune(kp: number[], ki: number[], kd: number[]): void {
    this.kp = kp; this.ki = ki; this.kd = kd;
  }

  reset(): void {
    this.integralError.fill(0);
    this.prevError.fill(0);
  }
}`,
      }),
      "game-module": () => ({
        name: "AutoGameAI", description: `Auto-generated game AI: ${prompt.slice(0, 80)}`,
        spec: {
          type: prompt.includes("behavior") ? "Behavior Tree" : prompt.includes("terrain") ? "Procedural Generator" : "Adaptive System",
          updateRate: "60Hz", memoryFootprint: "<2MB",
        },
        code: `// AutoGameAI — Auto-generated by Forge AI
export enum NodeStatus { SUCCESS, FAILURE, RUNNING }

export class BehaviorTree {
  private root: BTNode;

  constructor() {
    this.root = new Selector([
      new Sequence([ // Combat
        new Condition('enemyVisible'),
        new Selector([
          new Sequence([new Condition('healthLow'), new Action('flee')]),
          new Sequence([new Condition('hasAmmo'), new Action('attack')]),
          new Action('meleeAttack'),
        ]),
      ]),
      new Sequence([ // Patrol
        new Condition('hasPatrolRoute'),
        new Action('moveToNextWaypoint'),
        new Action('lookAround'),
      ]),
      new Action('idle'), // Fallback
    ]);
  }

  tick(blackboard: Map<string, any>): NodeStatus {
    return this.root.execute(blackboard);
  }
}

abstract class BTNode {
  abstract execute(bb: Map<string, any>): NodeStatus;
}

class Selector extends BTNode {
  constructor(private children: BTNode[]) { super(); }
  execute(bb: Map<string, any>) {
    for (const child of this.children) {
      const s = child.execute(bb);
      if (s !== NodeStatus.FAILURE) return s;
    }
    return NodeStatus.FAILURE;
  }
}

class Sequence extends BTNode {
  constructor(private children: BTNode[]) { super(); }
  execute(bb: Map<string, any>) {
    for (const child of this.children) {
      const s = child.execute(bb);
      if (s !== NodeStatus.SUCCESS) return s;
    }
    return NodeStatus.SUCCESS;
  }
}

class Condition extends BTNode {
  constructor(private key: string) { super(); }
  execute(bb: Map<string, any>) {
    return bb.get(this.key) ? NodeStatus.SUCCESS : NodeStatus.FAILURE;
  }
}

class Action extends BTNode {
  constructor(private action: string) { super(); }
  execute(bb: Map<string, any>) {
    console.log('Executing:', this.action);
    return NodeStatus.SUCCESS;
  }
}`,
      }),
    };

    const gen = configs[domain]();
    setTimeout(() => {
      resolve({
        id: `gen-${Date.now()}`, domain, ...gen, status: "ready", timestamp: Date.now(),
      });
    }, 2500 + Math.random() * 1500);
  });
}

export default function ForgeAIPage() {
  const [domain, setDomain] = useState<GenerationDomain>("solver");
  const [prompt, setPrompt] = useState("");
  const [generating, setGenerating] = useState(false);
  const [assets, setAssets] = useState<GeneratedAsset[]>([]);
  const [selectedAsset, setSelectedAsset] = useState<GeneratedAsset | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  const cfg = domainConfig[domain];

  const generate = async () => {
    if (!prompt.trim()) return;
    setGenerating(true);
    try {
      const asset = await simulateGeneration(domain, prompt);
      setAssets(prev => [asset, ...prev]);
      setSelectedAsset(asset);
      toast.success(`${asset.name} generated successfully`);
      setPrompt("");
    } catch {
      toast.error("Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="flex h-[calc(100vh-3.5rem)] overflow-hidden">
      {/* Left: Generator */}
      <div className="w-[480px] border-r flex flex-col">
        <div className="p-6 space-y-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Wand2 className="h-5 w-5 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">Forge AI</h1>
            </div>
            <p className="text-xs text-muted-foreground">Describe what you need. The SLM generates production-ready code in seconds.</p>
          </div>

          <Select value={domain} onValueChange={(v) => setDomain(v as GenerationDomain)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(domainConfig).map(([k, v]) => (
                <SelectItem key={k} value={k}>
                  <div className="flex items-center gap-2">
                    <v.icon className={cn("h-3.5 w-3.5", v.color)} />
                    {v.label}
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <div className="space-y-2">
            <Textarea
              placeholder={cfg.placeholder}
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              rows={4}
              className="resize-none"
              onKeyDown={e => { if (e.key === "Enter" && e.metaKey) generate(); }}
            />
            <Button className="w-full" onClick={generate} disabled={generating || !prompt.trim()}>
              {generating ? <><Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />Generating…</> : <><Sparkles className="h-3.5 w-3.5 mr-1.5" />Generate</>}
            </Button>
          </div>

          <div>
            <p className="text-[10px] text-muted-foreground font-medium mb-1.5 uppercase tracking-wider">Try these</p>
            <div className="space-y-1">
              {cfg.examples.map((ex, i) => (
                <button key={i} onClick={() => setPrompt(ex)}
                  className="text-xs text-left text-muted-foreground hover:text-foreground transition-colors w-full p-1.5 rounded hover:bg-muted/50 flex items-start gap-1.5"
                >
                  <ChevronRight className="h-3 w-3 mt-0.5 shrink-0 text-primary" />{ex}
                </button>
              ))}
            </div>
          </div>
        </div>

        <Separator />

        {/* History */}
        <ScrollArea className="flex-1 p-4">
          <p className="text-[10px] text-muted-foreground font-medium mb-2 uppercase tracking-wider">Generated ({assets.length})</p>
          <div className="space-y-2">
            {assets.map(a => {
              const Icon = domainConfig[a.domain].icon;
              return (
                <motion.div key={a.id} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }}
                  className={cn("p-3 rounded-lg border cursor-pointer transition-colors hover:bg-accent/10", selectedAsset?.id === a.id && "ring-2 ring-primary")}
                  onClick={() => setSelectedAsset(a)}
                >
                  <div className="flex items-center gap-2">
                    <Icon className={cn("h-3.5 w-3.5", domainConfig[a.domain].color)} />
                    <span className="text-sm font-medium truncate">{a.name}</span>
                    <Badge variant={a.status === "deployed" ? "default" : "secondary"} className="text-[9px] ml-auto shrink-0">{a.status}</Badge>
                  </div>
                  <p className="text-[10px] text-muted-foreground mt-1 line-clamp-1">{a.description}</p>
                </motion.div>
              );
            })}
            {assets.length === 0 && (
              <div className="text-center py-8 text-muted-foreground">
                <Sparkles className="h-8 w-8 mx-auto mb-2 opacity-30" />
                <p className="text-xs">No assets generated yet</p>
              </div>
            )}
          </div>
        </ScrollArea>
      </div>

      {/* Right: Asset viewer */}
      <div className="flex-1 flex flex-col min-w-0">
        <AnimatePresence mode="wait">
          {selectedAsset ? (
            <motion.div key={selectedAsset.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 flex flex-col">
              <div className="p-6 pb-0 flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold flex items-center gap-2">
                    <FileCode className="h-4 w-4 text-primary" />
                    {selectedAsset.name}
                  </h2>
                  <p className="text-xs text-muted-foreground mt-0.5">{selectedAsset.description}</p>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => { navigator.clipboard.writeText(selectedAsset.code); toast.success("Copied to clipboard"); }}>
                    <Copy className="h-3 w-3 mr-1" /> Copy
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => toast.info("Export dialog opened")}>
                    <Download className="h-3 w-3 mr-1" /> Export
                  </Button>
                  <Button size="sm" onClick={() => {
                    setAssets(prev => prev.map(a => a.id === selectedAsset.id ? { ...a, status: "deployed" } : a));
                    setSelectedAsset({ ...selectedAsset, status: "deployed" });
                    toast.success(`${selectedAsset.name} deployed to workspace`);
                  }}>
                    <Play className="h-3 w-3 mr-1" /> Deploy
                  </Button>
                </div>
              </div>

              {/* Spec cards */}
              <div className="p-6 pb-0">
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                  {Object.entries(selectedAsset.spec).filter(([, v]) => typeof v === "string").slice(0, 4).map(([k, v]) => (
                    <div key={k} className="p-2.5 rounded-md bg-muted/50 border">
                      <div className="text-[10px] text-muted-foreground capitalize">{k.replace(/([A-Z])/g, ' $1')}</div>
                      <div className="text-xs font-medium mt-0.5">{String(v)}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Code viewer */}
              <div className="flex-1 p-6 pt-4">
                <div className="h-full rounded-lg border bg-muted/30 overflow-hidden">
                  <div className="px-4 py-2 border-b bg-muted/50 flex items-center gap-2">
                    <Code2 className="h-3.5 w-3.5 text-muted-foreground" />
                    <span className="text-xs font-medium">Generated Code</span>
                    <Badge variant="outline" className="text-[9px] ml-auto">{selectedAsset.code.split("\n").length} lines</Badge>
                  </div>
                  <ScrollArea className="h-[calc(100%-36px)]">
                    <pre className="p-4 text-xs font-mono text-foreground/80 leading-relaxed whitespace-pre-wrap">{selectedAsset.code}</pre>
                  </ScrollArea>
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 flex items-center justify-center">
              <div className="text-center">
                <div className="h-16 w-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
                  <Wand2 className="h-8 w-8 text-primary" />
                </div>
                <h2 className="text-lg font-bold">Forge AI Generator</h2>
                <p className="text-sm text-muted-foreground mt-1 max-w-md">Pick a domain, describe what you need, and get production-ready code generated in seconds. Solvers, models, pipelines, controllers — all on demand.</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
