import { Link } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

const LAST_UPDATED = "March 10, 2026";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Button variant="ghost" size="sm" asChild className="mb-6">
          <Link to="/"><ArrowLeft className="h-4 w-4 mr-2" /> Back to Home</Link>
        </Button>

        <div className="flex items-center gap-3 mb-2">
          <FileText className="h-5 w-5 text-primary" />
          <h1 className="text-2xl font-bold">Terms of Service</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By accessing or using StackForge AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to modify these terms at any time; continued use constitutes acceptance.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. Account & Eligibility</h2>
            <ul className="text-sm text-muted-foreground space-y-1.5 list-disc pl-5">
              <li>You must be at least 18 years old to use the Service</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>One person or entity per account; sharing accounts is prohibited</li>
              <li>You must provide accurate and complete registration information</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. Subscriptions & Billing</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Paid plans (Builder, Pro) are billed monthly via Stripe. <strong>Subscriptions automatically renew</strong> at the end of each billing cycle unless canceled before the renewal date. You can cancel at any time through the customer portal; cancellation takes effect at the end of the current billing period.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Credits & Usage</h2>
            <ul className="text-sm text-muted-foreground space-y-1.5 list-disc pl-5">
              <li>Each plan includes a monthly credit allowance that resets each billing cycle</li>
              <li>Unused credits do not roll over to the next billing period</li>
              <li>Credit costs per AI model run vary and are listed on the Pricing page</li>
              <li>We reserve the right to adjust credit costs with 30 days' notice</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. Refund Policy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Subscription fees are non-refundable except where required by law. If you experience a technical issue that prevents you from using the Service, contact support within 7 days for a prorated credit. Credit top-up purchases are non-refundable once credits have been used.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. AI-Generated Content</h2>
            <ul className="text-sm text-muted-foreground space-y-1.5 list-disc pl-5">
              <li>AI outputs are generated by third-party models and provided "as-is"</li>
              <li>We do not guarantee the accuracy, completeness, or fitness of AI outputs</li>
              <li>You are responsible for reviewing and validating all AI-generated content before use</li>
              <li>You retain ownership of your inputs; outputs are licensed to you for your use</li>
              <li>You must not use the Service to generate content that violates any law</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Feature Access & Gating</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Certain features (e.g., Export Studio, Robotics, Edge Training) may be restricted to specific subscription tiers. Access to gated features requires an active subscription to the qualifying plan. Downgrading your plan may result in loss of access to premium features.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">8. Acceptable Use</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You agree not to: reverse-engineer or attempt to extract source code from the Service; use the Service to develop competing products; exceed rate limits or abuse the API; use automated tools to scrape or extract data; share, resell, or sublicense your account access.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">9. Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, StackForge AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">10. Termination</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may suspend or terminate your account if you violate these Terms. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately. We may retain anonymized data as described in our Privacy Policy.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-lg font-semibold text-foreground">11. Governing Law</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These Terms are governed by the laws of the jurisdiction in which StackForge AI operates, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
