import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY")!;

async function callAI(systemPrompt: string, userPrompt: string): Promise<string> {
  const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-2.5-flash",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    }),
  });
  if (!r.ok) throw new Error(`AI gateway: ${r.status}`);
  const j = await r.json();
  return j.choices?.[0]?.message?.content ?? "";
}

async function generateSLMBundle(config: any): Promise<{ filename: string; content: string }> {
  const baseModel = config.base_model ?? "llama-3.2-3b";
  const domain = config.domain ?? "general";
  const size = config.size ?? "small";
  const depth = config.depth ?? "shallow";
  const useCase = config.use_case ?? "";

  // Generate a seed corpus of instruction pairs
  const targetPairs = depth === "deep" ? 80 : depth === "standard" ? 40 : 20;
  const sys = `You generate high-quality JSONL training pairs for fine-tuning a small language model.
Output ONLY raw JSONL lines (one JSON object per line, no markdown, no commentary).
Each line: {"instruction": "...", "input": "", "output": "..."}`;
  const user = `Generate exactly ${targetPairs} diverse, domain-specialized training pairs for a small language model.
Domain: ${domain}
Specialization size: ${size}
Use case: ${useCase || "general purpose specialist"}
Vary difficulty, framing, and edge cases. Outputs should be concrete and accurate.`;

  const jsonl = await callAI(sys, user);

  const readme = `# Specific SLM Bundle — ${domain}

Base model: ${baseModel}
Size tier: ${size}
Depth: ${depth}
Pairs included: ~${targetPairs}

## Files
- \`train.jsonl\` — instruction-tuned training data
- \`README.md\` — this file
- \`train.py\` — local training entrypoint (uses Unsloth on GPU, transformers on CPU)
- \`config.json\` — base model + LoRA hyperparameters

## Quick start
\`\`\`bash
pip install unsloth transformers datasets accelerate
python train.py
\`\`\`

You own the resulting weights 100%. No royalties. No phone-home.
`;

  const trainPy = `# Auto-generated by SoupyLab Quick SLM
import os, json
from datasets import load_dataset

BASE = "${baseModel === 'llama-3.2-3b' ? 'unsloth/Llama-3.2-3B' : baseModel === 'phi-3-mini' ? 'unsloth/Phi-3-mini-4k-instruct' : 'unsloth/Qwen2.5-3B'}"
DATA = "train.jsonl"

try:
    from unsloth import FastLanguageModel
    import torch
    from trl import SFTTrainer
    from transformers import TrainingArguments
    model, tok = FastLanguageModel.from_pretrained(BASE, max_seq_length=2048, load_in_4bit=True)
    model = FastLanguageModel.get_peft_model(model, r=16, lora_alpha=16, target_modules=["q_proj","k_proj","v_proj","o_proj"])
    ds = load_dataset("json", data_files=DATA, split="train")
    def fmt(ex):
        return {"text": f"### Instruction:\\n{ex['instruction']}\\n\\n### Response:\\n{ex['output']}"}
    ds = ds.map(fmt)
    trainer = SFTTrainer(model=model, tokenizer=tok, train_dataset=ds, dataset_text_field="text",
        args=TrainingArguments(per_device_train_batch_size=2, gradient_accumulation_steps=4,
            num_train_epochs=3, learning_rate=2e-4, output_dir="./out"))
    trainer.train()
    model.save_pretrained_merged("./merged", tok, save_method="merged_16bit")
    print("Done. Merged model in ./merged")
except ImportError:
    print("Install unsloth, or run on CPU with vanilla transformers (slower).")
`;

  const configJson = JSON.stringify({
    base_model: baseModel,
    domain,
    size,
    depth,
    lora: { r: 16, alpha: 16 },
    epochs: 3,
    learning_rate: 2e-4,
  }, null, 2);

  // Bundle as a simple multi-file text package (we'll let the page download as ZIP via JSZip)
  const bundle = JSON.stringify({
    "train.jsonl": jsonl,
    "README.md": readme,
    "train.py": trainPy,
    "config.json": configJson,
  });

  return { filename: `slm-${domain}-${Date.now()}.json`, content: bundle };
}

async function generatePairsBundle(config: any): Promise<{ filename: string; content: string }> {
  const sources: string[] = config.sources ?? [];
  const fileTexts: string[] = config.file_texts ?? [];
  const target = Math.max(20, Math.floor(Number(config.estimated_pairs ?? 50)));
  const format = config.format ?? "instruction";

  const combined = [...fileTexts, ...sources].join("\n\n---\n\n").slice(0, 30000);

  const sys = `You convert raw source material into clean training pairs.
Output ONLY raw JSONL (one JSON object per line, no markdown).
Format: ${format === "dpo"
    ? '{"prompt": "...", "chosen": "...", "rejected": "..."}'
    : '{"instruction": "...", "input": "", "output": "..."}'}`;
  const user = `Generate exactly ${target} high-quality training pairs derived from the source material below.
Each pair must be specific, factually grounded in the source, and useful for fine-tuning.

SOURCE:
${combined}`;

  const jsonl = await callAI(sys, user);
  return {
    filename: `training-pairs-${Date.now()}.jsonl`,
    content: jsonl,
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } }
    );

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Not authenticated");
    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userErr } = await supabase.auth.getUser(token);
    if (userErr || !userData.user) throw new Error("Auth failed");
    const user = userData.user;

    const { job_id } = await req.json();

    const { data: job, error: jErr } = await supabase
      .from("paid_quick_jobs")
      .select("*")
      .eq("id", job_id)
      .eq("user_id", user.id)
      .maybeSingle();
    if (jErr || !job) throw new Error("Job not found");

    if (job.status === "ready") {
      // Re-issue signed URL
      const { data: signed } = await supabase.storage.from("quick-artifacts")
        .createSignedUrl(job.artifact_path, 3600);
      return new Response(JSON.stringify({ status: "ready", url: signed?.signedUrl, filename: job.artifact_filename }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }
    if (job.status !== "paid") throw new Error(`Job not paid (status: ${job.status})`);

    await supabase.from("paid_quick_jobs").update({ status: "generating" }).eq("id", job.id);

    let result: { filename: string; content: string };
    try {
      result = job.flow === "slm"
        ? await generateSLMBundle(job.config)
        : await generatePairsBundle(job.config);
    } catch (e) {
      await supabase.from("paid_quick_jobs").update({
        status: "failed",
        error_message: (e as Error).message,
      }).eq("id", job.id);
      throw e;
    }

    const path = `${user.id}/${job.id}/${result.filename}`;
    const { error: upErr } = await supabase.storage.from("quick-artifacts").upload(
      path,
      new Blob([result.content], { type: "application/octet-stream" }),
      { upsert: true }
    );
    if (upErr) throw upErr;

    await supabase.from("paid_quick_jobs").update({
      status: "ready",
      artifact_path: path,
      artifact_filename: result.filename,
      ready_at: new Date().toISOString(),
    }).eq("id", job.id);

    const { data: signed } = await supabase.storage.from("quick-artifacts")
      .createSignedUrl(path, 3600);

    return new Response(JSON.stringify({
      status: "ready",
      url: signed?.signedUrl,
      filename: result.filename,
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (e) {
    return new Response(JSON.stringify({ error: (e as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
